version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run:
          name: step1
          command: |
            pwd
            ls -l
            date
            sudo pip install urllib3
            git config --global user.name "absl-federation-github"
            git config --global user.email "absl-federation-github@google.com"
            git status
            rm federation_deps.bzl
            ./head_sync.py >> federation_deps.bzl
            git add federation_deps.bzl
            git status
            git commit -m "Update"

