version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7b:4a:9b:c5:80:53:6d:bd:ab:4f:a8:f5:13:3e:bb:c3"
      - run:
          name: step1
          command: |
            ls -l
            set -x
            echo "*********** install hub ********************************"
            wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz
            tar zxf hub-linux-amd64-2.12.3.tgz
            echo "************ install hub done! **************************"
            sudo pip install urllib3
            echo "************ install urllib3 done! **************************"
            git config --global user.name "absl-federation-github"
            git config --global user.email "absl-federation-github@google.com"
            #echo "************ git config done! **************************"
            BRANCH_NAME=$(date +%d-%b-%Y-daily)
            git checkout -b $BRANCH_NAME
            rm federation_deps.bzl
            ls -l
            time >> federation_deps.bzl
            git status
            git add federation_deps.bzl
            git commit -m "'$BRANCH_NAME'"
            echo "************ git status **************************"
            git status
            echo "************* making pr ***************************"
            ./hub-linux-amd64-2.12.3/bin/hub pull-request -p <<MSG
            $BRANCH_NAME
            MSG
            echo "**************************************************"








