version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - run:
          name: step1
          command: |
            pwd
            ls -l
            date
            pip install urllib3
            ./head_sync.py
