version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run:
          name: step1
          command: |
            pwd
            ls -l
            date
            echo "*********** install hub ********************************"
            wget https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz
            tar zxvf hub-linux-amd64-2.12.3.tgz
            ./hub-linux-amd64-2.12.3/bin/hub
            echo "************ install hub done! **************************"

            sudo pip install urllib3
            git config --global user.name "absl-federation-github"
            git config --global user.email "absl-federation-github@google.com"

            BRANCH_NAME=$(date +%d-%b-%Y-daily)
            git checkout -b $BRANCH_NAME

            rm federation_deps.bzl
            ./head_sync.py >> federation_deps.bzl
            git add federation_deps.bzl
            git commit -m $BRANCH_NAME
            git status







