version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run:
          name: step1
          command: |
            pwd
            ls -l
            date
            sudo pip install urllib3
            rm federation_deps.bzl
            ./head_sync.py >> federation_deps.bzl
            git config --global user.name "gennadiycivil"
            git status
            git add federation_deps.bzl
            git commit -m "Update"

