version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: step1
          command: |
            pwd
            ls -l
            date
            ./head_sync.py
